name: Repo B Workflow

on:
  repository_dispatch:
    types: [custom-event]

jobs:
  repo-b-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print message
        run: echo "Workflow triggered by Repo A"
